apiVersion: v1
kind: Service
metadata:
  name: planit-front-svc
  namespace: planit
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planit-front-deploy
  namespace: planit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: jybill01/planit-front:v0.9
        ports:
        - containerPort: 80
        env:
        - name: VITE_USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: planit-front-config
              key: VITE_USER_SERVICE_URL
        - name: VITE_SCHEDULE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: planit-front-config
              key: VITE_SCHEDULE_SERVICE_URL
        - name: VITE_INTELLIGENCE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: planit-front-config
              key: VITE_INTELLIGENCE_SERVICE_URL
        - name: VITE_INSIGHT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: planit-front-config
              key: VITE_INSIGHT_SERVICE_URL
        - name: VITE_COGNITO_USER_POOL_ID
          valueFrom:
            configMapKeyRef:
              name: planit-front-config
              key: VITE_COGNITO_USER_POOL_ID
        - name: VITE_COGNITO_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: planit-front-config
              key: VITE_COGNITO_CLIENT_ID
        - name: VITE_COGNITO_REGION
          valueFrom:
            configMapKeyRef:
              name: planit-front-config
              key: VITE_COGNITO_REGION
        - name: VITE_COGNITO_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: planit-front-config
              key: VITE_COGNITO_DOMAIN
        - name: VITE_COGNITO_REDIRECT_URI
          valueFrom:
            configMapKeyRef:
              name: planit-front-config
              key: VITE_COGNITO_REDIRECT_URI
