apiVersion: v1
kind: Service
metadata:
  name: planit-strategy-svc
  namespace: planit-dev
spec:
  selector:
    app: strategy
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: grpc
      port: 9093
      targetPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planit-strategy-deploy
  namespace: planit-dev
spec:
  selector:
    matchLabels:
      app: strategy
  template:
    metadata:
      labels:
        app: strategy
        tier: backend
        env: dev
    spec:
      serviceAccountName: planit-app-sa
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: planit-aws-secrets
      containers:
      - name: strategy
        image: 935875533840.dkr.ecr.ap-northeast-2.amazonaws.com/pi-strategy:c547621b2201a11e8f83c0dadb575c77acc35855
        ports:
        - containerPort: 8083
        - containerPort: 9093
        volumeMounts:
          - name: secrets-store
            mountPath: /mnt/secrets-store
            readOnly: true
        envFrom:
          - configMapRef:
              name: planit-strategy-config
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: SPRING_DATASOURCE_PASSWORD
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: AWS_ACCESS_KEY
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: AWS_SECRET_KEY
        - name: GNEWS_API_KEY
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: GNEWS_API_KEY
