apiVersion: v1
kind: Service
metadata:
  name: planit-insight-svc
  namespace: planit
spec:
  selector:
    app: insight
  ports:
    - name: http
      port: 8084
      targetPort: 8084
    - name: grpc
      port: 9094
      targetPort: 9094
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planit-insight-deploy
  namespace: planit
spec:
  selector:
    matchLabels:
      app: insight
  template:
    metadata:
      labels:
        app: insight
    spec:
      serviceAccountName: planit-app-sa
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: planit-aws-secrets
      containers:
      - name: insight
        image: jybill01/planit-insight:v0.3
        ports:
        - containerPort: 8084
        - containerPort: 9094
        volumeMounts:
          - name: secrets-store
            mountPath: /mnt/secrets-store
            readOnly: true
        envFrom:
          - configMapRef:
              name: planit-insight-config
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: SPRING_DATASOURCE_PASSWORD
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: AWS_SECRET_ACCESS_KEY
