apiVersion: v1
kind: ConfigMap
metadata:
  name: planit-user-config
  namespace: planit-dev
data:
  SERVER_PORT: "8081"
  GRPC_SERVER_PORT: "9091"
  PLANIT_USER_DB_URL: "jdbc:mariadb://pi-dev-mariadb.cbok2weui317.ap-northeast-2.rds.amazonaws.com:3306/planit_user_db"
  PLANIT_REDIS_HOST: "planit-redis-svc"
  PLANIT_CORS_ALLOWED_ORIGINS: "https://barumi-planit.store,http://localhost:3000,http://localhost:5173"
  SPRING_DATASOURCE_URL: "jdbc:mariadb://pi-dev-mariadb.cbok2weui317.ap-northeast-2.rds.amazonaws.com:3306/planit_user_db"
  REDIS_HOST: "planit-redis-svc"
  REDIS_PORT: "6379"
  AWS_REGION: "ap-northeast-2"
  COGNITO_USER_POOL_ID: "ap-northeast-2_GKpckavjT"
  COGNITO_CLIENT_ID: "6fjoogcqkvntfr9id76geuk2m7"
  SPRING_PROFILES_ACTIVE: "dev"
