apiVersion: v1
kind: Service
metadata:
  name: planit-schedule-svc
  namespace: planit-dev
spec:
  selector:
    app: schedule
  ports:
    - name: http
      port: 8082
      targetPort: 8082
    - name: grpc
      port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planit-schedule-deploy
  namespace: planit-dev
spec:
  selector:
    matchLabels:
      app: schedule
  template:
    metadata:
      labels:
        app: schedule
        tier: backend
        env: dev
    spec:
      serviceAccountName: planit-app-sa
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: planit-aws-secrets
      containers:
      - name: schedule
        image: 935875533840.dkr.ecr.ap-northeast-2.amazonaws.com/pi-schedule:88ef03d5676e7645406192670a3ebb083d33a9c7
        ports:
        - containerPort: 8082
        - containerPort: 9092
        volumeMounts:
          - name: secrets-store
            mountPath: /mnt/secrets-store
            readOnly: true
        envFrom:
          - configMapRef:
              name: planit-schedule-config
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: SPRING_DATASOURCE_PASSWORD
