apiVersion: v1
kind: ConfigMap
metadata:
  name: planit-insightai-config
  namespace: planit
data:
  APP_MODE: "grpc"
  PORT: "8085"
  GRPC_PORT: "9095"
  DB_HOST: "pi-dev-mariadb.cbok2weui317.ap-northeast-2.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "planit_insight_db"
  AWS_REGION: "ap-northeast-2"
  BEDROCK_MODEL_ID: "anthropic.claude-3-5-sonnet-20240620-v1:0"
  BEDROCK_MAX_TOKENS: "4000"
  BEDROCK_TEMPERATURE: "0.7"
