apiVersion: v1
kind: Service
metadata:
  name: planit-insightai-svc
  namespace: planit-dev
spec:
  selector:
    app: insightai
  ports:
    - name: http
      port: 8085
      targetPort: 8085
    - name: grpc
      port: 9095
      targetPort: 9095
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planit-insightai-deploy
  namespace: planit-dev
spec:
  selector:
    matchLabels:
      app: insightai
  template:
    metadata:
      labels:
        app: insightai
        tier: backend
        env: dev
    spec:
      serviceAccountName: planit-app-sa
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: planit-aws-secrets
      containers:
      - name: insightai
        image: 935875533840.dkr.ecr.ap-northeast-2.amazonaws.com/pi-insightai:976cd2d9cfc4aced798e1889f73b31b8ed2494b8
        ports:
        - containerPort: 8085
        - containerPort: 9095
        volumeMounts:
          - name: secrets-store
            mountPath: /mnt/secrets-store
            readOnly: true
        envFrom:
          - configMapRef:
              name: planit-insightai-config
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: DB_PASSWORD
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: planit-app-secrets
              key: AWS_SECRET_ACCESS_KEY
